apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote:before
        name: vote-app
        resources:
         requests:
          cpu: 2m
        
---
apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: vote
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
    

  selector:
    app: vote     
      
